language: go

go:
  - 1.6

install:
  - go get -u github.com/golang/lint/golint

script:
  - golint $(go list ./... | grep -v /vendor/)
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
